### ISSUE TITLE
Retrieving Youtube videos as audio files

### ISSUE THREAD

**Issue by aashishyadavally** [aashishyadavally/Hindi-Speech-Corpus#2]
@shriadke : Can you update 'src/links.txt' with the links of Youtube Hindi News videos that we need? Accordingly, when you run the script, mp3 files will be added into the 'audios' folder in the same directory, which can then be further cut into speech samples.

**Comment by shriadke** [comment]
Added 5 Files which will be around an hour of speech data

**Comment by aashishyadavally** [comment]
@shriadke I think the second link is of a playlist. Can we get one of the audio file individually?
